version: '3.8'

services:
  backend:
    container_name: backend_node_ts
    build:
      context: ./server
    restart: unless-stopped
    ports:
      - '${PORT}:5000'
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DB_URL=${DB_URL}
  frontend:
    container_name: frontend_vue_ts
    build:
      context: ./client
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - '3000:3000'